config/routes.rb
Calmecac::Application.routes.draw do
  
  get 'curso_profesor/:profesor_id/:curso_id', :controller => :cursos_profesores, :action => 'curso_profesor'

  resources :autenticaciones

  devise_for :usuarios, :controllers => {:registrations => 'registrations'}
  
  # Match con la response de los provedores de redes sociales
  match '/auth/:provider/callback' => 'autenticaciones#create'

  match 'sobre_nosotros' => 'pages#about_us', :as => :about_us
  match 'terminos_de_uso' => 'pages#terms_of_use', :as => :terms_of_use
  match 'privacidad' => 'pages#privacy', :as => :privacy
  match 'aviso_legal' => 'pages#legal_advisor', :as => :legal_advisor
  match 'faqs' => 'pages#faqs', :as => :faqs
  match 'registrate' => 'usuarios#sign_up', :as => :signup
  match 'inicia_sesion' => 'sessions#sign_in', :as => :login

  match 'contacto' => 'contact#new', :as => 'contact', :via => :get
  match 'contacto' => 'contact#create', :as => 'contact', :via => :post
  
  match 'share_buttons' => 'pages#share_buttons', :as => :share_buttons
  
  # Para invitacion masiva de contactos. Implementacion no habilitada a los usuarios. 
  #match 'invitar' => 'invitation#new', :as => 'invitation', :via => :get
  #match 'invitar' => 'invitation#create', :as => 'invitation', :via => :post
  

  get 'pages/mas_resultados'
  
  resources :universidades, :shallow => true do
    
    collection do
      get "mas_universidades"
    end
    
    resources :campus, :shallow => true do
      collection do
        get "mas_resultados"
      end      
      
      resources :cursos do
        collection do
          get "mas_resultados"
        end        
      end
    end
  end

  resources :calificaciones, :only => [:create] do
    member do
      post 'like'
      post 'flag'
    end
  end
  
  resources :profesores do
    collection do
      get "mas_resultados"
    end
  end
  
  resources :comentarios, :only => [:create]

  root :to => redirect("/usuarios/sign_in")

end

app/controllers/cursos_profesores_controller.rb
class CursosProfesoresController < ApplicationController
  
  def curso_profesor
    @profesor = Profesor.find(params[:profesor_id])
    @curso_profesor = @profesor.curso_profesor.find_by_curso_id(params[:curso_id],
                      :include => { :calificaciones => [ {:comentarios => :usuario}, :likes, :usuario]})
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/views/cursos_profesores/_calificaciones.html.erb
<div id="calificaciones_curso_profesor_<%= curso_profesor.curso_id %>_<%= curso_profesor.profesor_id %>">
  <%= render curso_profesor.calificaciones %>
</div>

<br/>

<% if current_usuario == nil %>
  <%= link_to 'Iniciar Sesión', new_usuario_session_path %>
    <%= link_to (image_tag "twitter_16.png"), "/auth/twitter" %>
		<%= link_to (image_tag "facebook_16.png"), "/auth/facebook" %>
  o
  <%= link_to 'registrate', new_usuario_registration_path %> para comentar

<% elsif !curso_profesor.calificaciones.find_by_usuario_id(current_usuario.id) %>
<div id="calificaciones_form">
		<%= render :partial => 'calificaciones/form', :locals => {:calificacion => Calificacion.new, 
															  	  :curso_profesor_id => curso_profesor.id} %>
</div>
<% else %>
  <%= render 'cursos_profesores/ya_comento' %>
<% end %>

app/views/cursos_profesores/_curso_profesor.html.erb
<div class="columns on-3 profesor-entry">
  <div class="container wrapper">
    <div class="column fixed image" style="width: 172px">
      <div class="container">
        <%= link_to (image_tag curso_profesor.profesor.avatar_url(:thumb).to_s), profesor_path(curso_profesor.profesor) %>
      </div>
    </div>
    <div class="column fixed info" style="width: 415px">
      <div class="container">
        <h3>
          <% if can? :read, curso_profesor.profesor %>
            <%= link_to truncate(curso_profesor.profesor.nombre_completo, :length => 23 ),
                        profesor_path(curso_profesor.profesor,
                        :anchor => "curso_profesor_#{curso_profesor.curso.id}_#{curso_profesor.profesor.id}"),
                        :title => curso_profesor.profesor.nombre_completo, :class => "tooltip" %>
          <% end %>
        </h3>
        <h4>
          <%= link_to truncate(curso_profesor.curso.nombre, :length => 40),
                      profesor_path(curso_profesor.profesor,
                      :anchor => "curso_profesor_#{curso_profesor.curso.id}_#{curso_profesor.profesor.id}"),
                      :title => curso_profesor.curso.nombre, :class => "tooltip" %>
        </h4>
        <span id="editar_profesor" class="edit_profesor">
          <%= link_to 'Editar', edit_profesor_path(curso_profesor.profesor) if can? :edit, curso_profesor.profesor %>
        </span>
        <div class="universidades">
          <%= render 'shared/universidad_campus', :universidad => curso_profesor.curso.universidad,
                                                  :campus => curso_profesor.curso.campus %>
        </div>
      </div>
    </div>
    <div class="column fixed rating" style="width: 121px">
      <div class="container">
        <div class="calif">
          <div class="label">Calificaci&oacute;n</div>
          <div class="amount"><%= curso_profesor.promedio_promedio %></div>
        </div>
        <div class="calif resen">
          <div class="label">Rese&ntilde;as</div>
          <div class="amount"><%= curso_profesor.calificaciones.size %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cursos_profesores/_profesor_detalles.html.erb
<p>Reseñas del profesor: <span id="amount_profesor"><%= profesor.calificaciones.size %></span></p>
<br />
<br />

<h2><span id="amount_curso_profesor"><%= curso_profesor.calificaciones.size %></span> Reseñas del curso <%= curso_profesor.curso.nombre %></h2>

<table id="profesor_averages">
 <%= render :partial => 'calificaciones/tabla_promedios',
            :locals => {:curso_profesor => curso_profesor} %>
</table>

app/views/cursos_profesores/_ya_comento.html.erb
<div id="ha_comentado">
  <h4>Ya has comentado aquí, ¡gracias!</h4>
</div>

app/views/cursos_profesores/curso_profesor.js.erb
$("#curso_profesor_<%= params[:curso_id]%>_<%= params[:profesor_id] %>")
	.html("<%= escape_javascript(render :partial => 'calificaciones', :locals => {:curso_profesor => @curso_profesor}) %>");

$("#caracteristicas_profesor")
	.html("<%= escape_javascript(render :partial => 'profesor_detalles', :locals => {:profesor => @profesor, :curso_profesor => @curso_profesor})%>");
	
$("input.star").rating();