config/routes.rb
Calmecac::Application.routes.draw do
  
  get 'curso_profesor/:profesor_id/:curso_id', :controller => :cursos_profesores, :action => 'curso_profesor'

  resources :autenticaciones

  devise_for :usuarios, :controllers => {:registrations => 'registrations'}
  
  # Match con la response de los provedores de redes sociales
  match '/auth/:provider/callback' => 'autenticaciones#create'

  match 'sobre_nosotros' => 'pages#about_us', :as => :about_us
  match 'terminos_de_uso' => 'pages#terms_of_use', :as => :terms_of_use
  match 'privacidad' => 'pages#privacy', :as => :privacy
  match 'aviso_legal' => 'pages#legal_advisor', :as => :legal_advisor
  match 'faqs' => 'pages#faqs', :as => :faqs
  match 'registrate' => 'usuarios#sign_up', :as => :signup
  match 'inicia_sesion' => 'sessions#sign_in', :as => :login

  match 'contacto' => 'contact#new', :as => 'contact', :via => :get
  match 'contacto' => 'contact#create', :as => 'contact', :via => :post
  
  match 'share_buttons' => 'pages#share_buttons', :as => :share_buttons
  
  # Para invitacion masiva de contactos. Implementacion no habilitada a los usuarios. 
  #match 'invitar' => 'invitation#new', :as => 'invitation', :via => :get
  #match 'invitar' => 'invitation#create', :as => 'invitation', :via => :post
  

  get 'pages/mas_resultados'
  
  resources :universidades, :shallow => true do
    
    collection do
      get "mas_universidades"
    end
    
    resources :campus, :shallow => true do
      collection do
        get "mas_resultados"
      end      
      
      resources :cursos do
        collection do
          get "mas_resultados"
        end        
      end
    end
  end

  resources :calificaciones, :only => [:create] do
    member do
      post 'like'
      post 'flag'
    end
  end
  
  resources :profesores do
    collection do
      get "mas_resultados"
    end
  end
  
  resources :comentarios, :only => [:create]

  root :to => redirect("/usuarios/sign_in")

end

app/models/campu.rb
class Campus < ActiveRecord::Base
end

app/models/campus.rb
# == Schema Information
#
# Table name: campus
#
#  id             :integer(4)      not null, primary key
#  nombre         :string(255)
#  ciudad         :string(255)
#  estado         :string(255)
#  universidad_id :integer(4)
#  created_at     :datetime
#  updated_at     :datetime
#

class Campus < ActiveRecord::Base

  belongs_to :universidad
  has_many :cursos, :dependent => :destroy
  has_many :profesores, :dependent => :destroy
  has_many :usuarios
  has_many :propuestas
  
  extend FriendlyId
  friendly_id :nombre, use: :slugged  #=> In production: Campus.find_each(&:save)

  validates :nombre, :uniqueness => {:scope => :universidad_id},
                     :presence => true

  def to_s
    nombre
  end
  
end

app/controllers/campus_controller.rb
class CampusController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :mas_resultados

  def index
    load_campus

    respond_to do |format|
      format.html
      format.json { render :json => @campus.map(&:attributes) }
      format.js
    end
  end
  
  def mas_resultados
    authorize! :read, Campus
    load_campus
  end
  
  def show
    @campus = Campus.find(params[:id])
  end

  def new
    @universidad = Universidad.find(params[:universidad_id])
    @campus = @universidad.campus.build
  end

  def edit
    @campus = Campus.find(params[:id])
  end

  def create
    @universidad = Universidad.find(params[:universidad_id])
    @campus = @universidad.campus.build(params[:campus])

      if @campus.save
        redirect_to(@campus, :notice => 'Campus was successfully created.')
      else
        render :action => "new"
      end
  end

  def update
    @campus = Campus.find(params[:id])

      if @campus.update_attributes(params[:campus])
         redirect_to(@campus, :notice => 'Campus was successfully updated.') 
      else
         render :action => "edit"
      end
  end

  def destroy
    @campus = Campus.find(params[:id])
    @campus.destroy
    redirect_to(universidad_campus_index_url(@campus.universidad))
  end
  
  def load_campus
    @universidad = Universidad.find(params[:universidad_id])
    @campus = @universidad.campus.where("nombre LIKE ?", "%#{params[:q]}%").page(params[:page]).per(10) 
    @campus = @campus.scoped(:include => [:cursos, :profesores])
  end
  
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/views/campus/_campus.html.erb
<div class="columns on-3 profesor-entry">
  <div class="container wrapper">
    <div class="column fixed image" style="width: 30px">
      <div class="container">
      </div>
    </div>
    <div class="column fixed info" style="width: 400px">
      <div class="container">
        <h1 class="resource-link">
          <% if can? :read, campus %>
            <%= link_to truncate(campus.nombre, :length => 23), campus_cursos_path(campus), :title => campus.nombre, :class => "tooltip display_campus" %>
          <% end %>
        </h1>
<br />
				<p><span><%= pluralize(campus.cursos.size, "Curso") %></span> | <span><%= pluralize(campus.profesores.size, "Profesor") %></span></p>
      </div>
    </div>
    <div class="column fixed place" style= "width: 200px">
      <div class="container date">
        <h4><%= campus.ciudad %>, <%= campus.estado %></h4>
      </div>
    </div>
  </div>
</div>

app/views/campus/_form.html.erb
<%= form_for [@universidad,@campus] do |f| %>
  <% if @campus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campus.errors.count, "error") %> prohibited this campus from being saved:</h2>

      <ul>
      <% @campus.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br />
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :universidad_id %><br />
    <%= f.text_field :universidad_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campus/edit.html.erb
<h1>Editing campus</h1>

<%= render 'form' %>

<%= link_to 'Show', @campus if can? :read, @campus %>
<%= link_to 'Back', universidad_campus_index_path(@campus.universidad) %>

app/views/campus/index.html.erb
<% content_for :header do %>
  <h1>Campus en <%= @universidad %></h1>
<% end %>

<div id="info-profesores" class="columns on-2">
  <div class="column">
    <%= form_tag(universidad_campus_index_path(@universidad), :method => :get, :autocomplete => "off", :class => "generic-form") do  %>
	    <%= text_field_tag :q, params[:q], "data-observe" => "true" %>
	    <%= submit_tag "Buscar Campus", :name => nil %>
	    <%= image_tag 'ajax-loader.gif', :class => "loading", :style => "display:none;" %>
    <% end %>
  </div>
  <div class="column">
  </div>
</div>

<br/>
<h3>Se encontraron <span id="resultados"><%= @campus.total_count %></span> resultados</h3>
<br />

<div id="listado">
	<%= render @campus %>
</div>
<br />

<%= link_to "Nuevo Campus", new_universidad_campus_path(@universidad) if can? :create, Campus %>

<div id="next_link">
  <%= render :partial => 'shared/show_more', :object => @campus,
              :locals => { :url => mas_resultados_universidad_campus_index_path(@universidad),
              :parametros => { :q => :q } } %>
</div>

app/views/campus/index.js.erb
$("#listado").html("<%= escape_javascript(render @campus) %>");

<%
	show_more = escape_javascript(render(:partial => 'shared/show_more', :object => @campus,
            														:locals => { :url => mas_resultados_universidad_campus_index_path(@universidad),
																											:parametros => {  :q => :q}
																																			}
																				)
																)

%>

$("#next_link").html("<%= show_more %>");
$("#resultados").html("<%= @campus.total_count %>");

<% if @campus.current_page >= @campus.num_pages %>
  $("#next_link").css("display", "none");
<% else %>
   $("#next_link").css("display", "block");
<% end %>

app/views/campus/mas_resultados.js.erb
$("#listado").append("<%= escape_javascript(render @campus)%>");
$("#page").val(<%= @campus.current_page + 1 %>);

<% if @campus.current_page >= @campus.num_pages %>
  $("#next_link").css("display", "none");
<% else %>
   $("#next_link").css("display", "block");
<% end %>

app/views/campus/new.html.erb
<h1>New campus</h1>

<%= render 'form' %>

<%= link_to 'Back', universidad_campus_index_path(@universidad) %>

app/views/campus/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @campus.nombre %>
</p>

<p>
  <b>Ciudad:</b>
  <%= @campus.ciudad %>
</p>

<p>
  <b>Estado:</b>
  <%= @campus.estado %>
</p>

<p>
  <b>Universidad:</b>
  <%= @campus.universidad_id %>
</p>

<%= link_to 'Cursos', campus_cursos_path(@campus) if can? :read, @campus %>
<%= link_to 'Edit', edit_campus_path(@campus) if can? :edit, @campus %>
<%= link_to 'Back', universidad_campus_index_path(@campus.universidad) %>