config/routes.rb
Calmecac::Application.routes.draw do
  
  get 'curso_profesor/:profesor_id/:curso_id', :controller => :cursos_profesores, :action => 'curso_profesor'

  resources :autenticaciones

  devise_for :usuarios, :controllers => {:registrations => 'registrations'}
  
  # Match con la response de los provedores de redes sociales
  match '/auth/:provider/callback' => 'autenticaciones#create'

  match 'sobre_nosotros' => 'pages#about_us', :as => :about_us
  match 'terminos_de_uso' => 'pages#terms_of_use', :as => :terms_of_use
  match 'privacidad' => 'pages#privacy', :as => :privacy
  match 'aviso_legal' => 'pages#legal_advisor', :as => :legal_advisor
  match 'faqs' => 'pages#faqs', :as => :faqs
  match 'registrate' => 'usuarios#sign_up', :as => :signup
  match 'inicia_sesion' => 'sessions#sign_in', :as => :login

  match 'contacto' => 'contact#new', :as => 'contact', :via => :get
  match 'contacto' => 'contact#create', :as => 'contact', :via => :post
  
  match 'share_buttons' => 'pages#share_buttons', :as => :share_buttons
  
  # Para invitacion masiva de contactos. Implementacion no habilitada a los usuarios. 
  #match 'invitar' => 'invitation#new', :as => 'invitation', :via => :get
  #match 'invitar' => 'invitation#create', :as => 'invitation', :via => :post
  

  get 'pages/mas_resultados'
  
  resources :universidades, :shallow => true do
    
    collection do
      get "mas_universidades"
    end
    
    resources :campus, :shallow => true do
      collection do
        get "mas_resultados"
      end      
      
      resources :cursos do
        collection do
          get "mas_resultados"
        end        
      end
    end
  end

  resources :calificaciones, :only => [:create] do
    member do
      post 'like'
      post 'flag'
    end
  end
  
  resources :profesores do
    collection do
      get "mas_resultados"
    end
  end
  
  resources :comentarios, :only => [:create]

  root :to => redirect("/usuarios/sign_in")

end

app/models/propuesta.rb
class Propuesta < ActiveRecord::Base
  acts_as_voteable
  belongs_to :usuario
  belongs_to :campus
  has_many :votes, :as => :voteable
  has_many :propuestas_tags, :class_name =>"PropuestaTag", :dependent => :destroy
  has_many :tags, :through => :propuestas_tags
  
  accepts_nested_attributes_for :tags
  
  attr_accessible :titulo, :descripcion, :categoria, :votos, :usuario_id, :tags_tokens, :tags_attributes
  
  validates :titulo, :descripcion, presence: true
  
  attr_reader :tags_tokens
  
  accepts_nested_attributes_for :tags
    
  def tags_tokens=(ids)
    ids = ids.split(",")
    ids.delete_if{ |i| i.include?("new") }
    self.tag_ids = ids
  end
  
  alias_method :votos, :votes_count
  
end

app/controllers/propuestas_controller.rb
class PropuestasController < ApplicationController
  load_and_authorize_resource

  def index
    @campus = Campus.find(params[:campus_id])
    @propuestas = @campus.propuestas.order(params[:orden]).page(params[:page]).per(10)
  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @propuestas }
      format.js
    end
  end
  
  def mis_votos
    @campus = Campus.find(params[:campus_id])
    @propuestas = Propuesta.joins(:votes).where("votes.voter_id" => current_usuario).page(params[:page]).per(10)
  
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @propuestas }
      format.js { render 'index.js' }
    end
  end
  
  def mis_propuestas
    @campus = Campus.find(params[:campus_id])
    @propuestas = current_usuario.propuestas.page(params[:page]).per(10)

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @propuestas }
      format.js { render 'index.js' }
    end
  end

  def show
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @propuesta }
    end
  end

  def new
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @propuesta }
    end
  end

  def edit
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.find(params[:id])
  end

  def create
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.build(params[:propuesta])
    @propuesta.usuario_id = current_usuario.id    #TODO verificar que usuarios no loggeados

    nuevos_tags
    
    if @propuesta.save
      redirect_to(campus_propuesta_path(@campus, @propuesta), :notice => 'Propuesta was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.build(params[:propuesta])
    
    nuevos_tags
    
    if @propuesta.update_attributes(params[:propuesta])
      redirect_to(campus_propuesta_path(@campus, @propuesta), :notice => 'Propuesta was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @campus = Campus.find(params[:campus_id])
    @propuesta = @campus.propuestas.find(params[:id])
    @propuesta.destroy

    redirect_to campus_propuestas_path(@campus)
  end
  
  def vote_up
    begin
      #TODO verificar si usuario no esta loggeado
      @campus = Campus.find(params[:campus_id])
      current_usuario.vote_for(@propuesta = Propuesta.find(params[:id]))
      #redirect_to campus_propuesta_path(@campus, @propuesta)
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end
  
  private
  
  def nuevos_tags
    @new_tags = @propuesta.tags.reject{ |c| !c.new_record? }
  end
end

app/helpers/propuestas_helper.rb
module PropuestasHelper
end

app/views/propuestas/_form.html.erb
<%= form_for([@campus, @propuesta], :url => {:controller => :propuestas, :action => (@propuesta.new_record? ? :create : :update) }) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  
  <div class="field">
		<%= f.label :tags_tokens, "Tags:" %>
		<%= f.text_field :tags_tokens, "data-pre" => @propuesta.tags.map(&:attributes).to_json, :id => 'tags_propuestas' %>

  	<% @new_tags.try :each_with_index, do |curso, i| %>
  	  <%= hidden_field_tag "propuesta[tags_attributes][#{Time.now.to_i + i}][nombre]", curso %>
  	<% end %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/propuestas/_propuestas.html.erb
<table>
  <tr>
    <th>Votos</th> 
    <th>Titulo</th>
    <th>Descripcion</th>
    <th>Tags</th>
    <th>Creador</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @propuestas.each do |propuesta| %>
  <tr>
    <td><%= propuesta.votos %></td>
    <td><%= propuesta.titulo %></td>
    <td><%= propuesta.descripcion %></td>
    <td><%= propuesta.tags.join(", ") %></td>
    <td><%= propuesta.usuario.username  %></td>
    <td><%= link_to 'Show', campus_propuesta_path(@campus, propuesta) %></td>
    <td><%= link_to 'Edit', edit_campus_propuesta_path(@campus, propuesta) %></td>
    <td><%= link_to 'Destroy', campus_propuesta_path(@campus, propuesta), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= paginate @propuestas, :remote => true %>

app/views/propuestas/edit.html.erb
<h1>Editing propuesta</h1>

<%= render 'form' %>

<%= link_to 'Show', campus_propuesta_path(@campus, @propuesta) %> |
<%= link_to 'Back', campus_propuestas_path(@campus) %>

app/views/propuestas/index.html.erb
<% content_for :header do %>
  <h1>Propuestas en <%= @campus.nombre %></h1>
<% end %>

<%= link_to 'Populares', campus_propuestas_path(@campus, :orden => "votes_count desc"), :remote => true %>
<%= link_to 'Recientes', campus_propuestas_path(@campus, :orden => "created_at desc"), :remote => true %>
<%= link_to 'Mis Propuestas', mis_propuestas_campus_propuestas_path(@campus), :remote => true if can? :mis_propuestas, Propuesta %>
<%= link_to 'Mis Votos', mis_votos_campus_propuestas_path(@campus), :remote => true if can? :mis_votos, Propuesta %>

<div id="listado_propuestas">
  <%= render 'propuestas' %>
</div>

<br />

<%= link_to 'Nueva Propuesta', new_campus_propuesta_path(@campus) %>

app/views/propuestas/index.js.erb
$('#listado_propuestas').html("<%= escape_javascript(render 'propuestas') %>");

var url_actual = $(location).attr('href').split('?')[0];
var params = [];
<% if params[:page].present? %>
  params.push("page=" + <%= params[:page] %>);
<% end %>
<% if params[:orden].present? %>
  params.push("orden=" + "<%= params[:orden].gsub(' ', '+') %>");
<% end %>
params = (params.length == 0 ? "" : "?") + params.join('&');
history.replaceState(null, document.title, url_actual + params);

app/views/propuestas/new.html.erb
<h1>Nueva propuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', campus_propuestas_path(@campus) %>

app/views/propuestas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Votos: </b><span id="votes_count"><%= @propuesta.votos %></span>
</p>

<p>
  <b>Titulo:</b>
  <%= @propuesta.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @propuesta.descripcion %>
</p>

<p>
  <b>Tags:</b>
  <%= @propuesta.tags.join(', ') %>
</p>

<p>
  <b>Sugerida por:</b>
  <%= @propuesta.usuario.username %>, <%= @propuesta.created_at.time.strftime("%d/%m/%Y") %>
</p>

<br />
<% if usuario_signed_in? %>
  <% if current_usuario.voted_on?(@propuesta) %>
    <div>VOTADO</div>
  <% elsif current_usuario.id == @propuesta.usuario_id %>
    <div>Yo la cree</div>
  <% else %>
    <div id="votos">
    <%= link_to 'vote up', vote_up_campus_propuesta_path(@campus, @propuesta), :remote => true, :method => :post, :id => "voto_favor" %>
    </div>
  <% end %>
<% else %>
  <div>Regístrate para apoyar la iniciativa</div>
<% end %>

<%= link_to 'Edit', edit_campus_propuesta_path(@campus, @propuesta) %> |
<%= link_to 'Back', campus_propuestas_path(@campus) %>

app/views/propuestas/vote_up.js.erb
$('#votes_count').html(<%= @propuesta.votos + 1 %>)
$('#voto_favor').remove();
$('div#votos').html("Ya vote");